@MinimalApiStructure_HostAddress = https://localhost:7144

POST {{MinimalApiStructure_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true,
  "Secret": "yes"
}
###

GET {{MinimalApiStructure_HostAddress}}/todoitems

###

GET {{MinimalApiStructure_HostAddress}}/todoitems/4

###

PUT {{MinimalApiStructure_HostAddress}}/todoitems/2
Content-Type: application/json

{
  "id": 3,
  "name": "feed fish",
  "isComplete": false
}
###

GET {{MinimalApiStructure_HostAddress}}/todoitems/complete

###

DELETE {{MinimalApiStructure_HostAddress}}/todoitems/1

###
